name: build
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.4, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add pip bin to PATH
        run: |
          echo "::add-path::/home/runner/.local/bin"

      - name: Install deps with ${{ matrix.python-version }}
        run: pip install .[test, lint]

      - name: Lint with ${{ matrix.python-version }}
        if: ${{ matrix.python-version == '3.8' }}
        run: |
          black --check stream
          flake8 --ignore=E501,E225,W293,W503 stream

      - name: Install, test and code coverage with ${{ matrix.python-version }}
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
          STREAM_SECRET: ${{ secrets.STREAM_SECRET }}
        run: |
          python setup.py test
          python setup.py install
          codecov
